version: '3.8'

services:
  calendar:
    build: .
    container_name: dj-calendar
    ports:
      - "3000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - calendar-network

networks:
  calendar-network:
    driver: bridge 